title: Jessy Min
description: Data Analyst on the Road

url: http://jessymin.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Fallback image and color
image:               /assets/img/work_and_life.jpg
color:               '#4f86aa'

markdown: kramdown
highlighter: rouge
kramdown:
  footnote_backlink: '&#x21a9;&#xfe0e;'
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Blog
   url: /index.html
 - title: About
   url: /about
 - title : Archive
   url: /archive
 - title: Category
   url: /category
 - title : Project
   url : /project

social:
   github: jessymin
   facebook:

google_analytics: "UA-58263416-1***"

theme: jekyll-theme-slate
