title: Jessy Min 
description: 고객을 이해하기 위한 데이터분석의 길

url: http://jessymin.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Blog
   url: /index.html
 - title: About
   url: /about

social:
   github: jessymin
   facebook: jessymin

google_analytics: "UA-58263416-1***"
