title: Jessy Min 
description: Data Analyst on the Road

url: http://jessymin.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Blog
   url: /index.html
 - title: About
   url: /about
 - title : Archive
   url: /archive
 - title: Category
   url: /category
 - title : Project
   url : /project

social:
   github: jessymin
   facebook: jessy.min.75

google_analytics: "UA-58263416-1***"

theme: jekyll-theme-slate
